version: '3.7'
services:
  backend:
    # or image: diogo8machado/vuttr
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      APP_SECRET: test
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: docker
      DB_NAME: VUTTR
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: VUTTR
    volumes:
      - pg_data_VUTTR:/var/lib/postgresql/data

volumes:
  pg_data_VUTTR:
